### ISSUE TITLE
about the conditioning_timestep parameter in train_sd.py

### ISSUE THREAD

**Issue by Jason-Chi-xx** [SYZhang0805/DisBack#1]
Can I ask why the conditioning_timestep is set to 399 instead of 999 when running train_sd.py ? Thanks

**Comment by SYZhang0805** [comment]
In the implementation of [DMD2] (https://github.com/tianweiy/DMD2), the conditioning_timestep is set to 399. We have tried to use other values, but the generation samples are not good. Timestep=399 may be an optimal value to generate the best results.

**Comment by Jason-Chi-xx** [comment]
I see. Thanks for your reply
